server:
  port: 8090

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mbti
    username: root
    password: admin!testdb123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
